# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sk8_calibration_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1026, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblPort = QtWidgets.QLabel(self.centralwidget)
        self.lblPort.setObjectName("lblPort")
        self.verticalLayout.addWidget(self.lblPort)
        self.lblDevices = QtWidgets.QLabel(self.centralwidget)
        self.lblDevices.setObjectName("lblDevices")
        self.verticalLayout.addWidget(self.lblDevices)
        self.lstDevices = QtWidgets.QListView(self.centralwidget)
        self.lstDevices.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lstDevices.setObjectName("lstDevices")
        self.verticalLayout.addWidget(self.lstDevices)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnRefresh = QtWidgets.QPushButton(self.centralwidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout.addWidget(self.btnRefresh)
        self.btnCancelScan = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelScan.setObjectName("btnCancelScan")
        self.horizontalLayout.addWidget(self.btnCancelScan)
        self.btnConnect = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout.addWidget(self.btnConnect)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.btnMag = QtWidgets.QPushButton(self.centralwidget)
        self.btnMag.setEnabled(False)
        self.btnMag.setObjectName("btnMag")
        self.gridLayout.addWidget(self.btnMag, 3, 0, 1, 1)
        self.btnGyro = QtWidgets.QPushButton(self.centralwidget)
        self.btnGyro.setEnabled(False)
        self.btnGyro.setObjectName("btnGyro")
        self.gridLayout.addWidget(self.btnGyro, 2, 0, 1, 1)
        self.dataAccX = QtWidgets.QLineEdit(self.centralwidget)
        self.dataAccX.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataAccX.setAlignment(QtCore.Qt.AlignCenter)
        self.dataAccX.setObjectName("dataAccX")
        self.gridLayout.addWidget(self.dataAccX, 1, 1, 1, 1)
        self.dataAccY = QtWidgets.QLineEdit(self.centralwidget)
        self.dataAccY.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataAccY.setAlignment(QtCore.Qt.AlignCenter)
        self.dataAccY.setObjectName("dataAccY")
        self.gridLayout.addWidget(self.dataAccY, 1, 2, 1, 1)
        self.btnAcc = QtWidgets.QPushButton(self.centralwidget)
        self.btnAcc.setEnabled(False)
        self.btnAcc.setObjectName("btnAcc")
        self.gridLayout.addWidget(self.btnAcc, 1, 0, 1, 1)
        self.dataGyroX = QtWidgets.QLineEdit(self.centralwidget)
        self.dataGyroX.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataGyroX.setAlignment(QtCore.Qt.AlignCenter)
        self.dataGyroX.setObjectName("dataGyroX")
        self.gridLayout.addWidget(self.dataGyroX, 2, 1, 1, 1)
        self.dataMagX = QtWidgets.QLineEdit(self.centralwidget)
        self.dataMagX.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataMagX.setAlignment(QtCore.Qt.AlignCenter)
        self.dataMagX.setObjectName("dataMagX")
        self.gridLayout.addWidget(self.dataMagX, 3, 1, 1, 1)
        self.dataMagZ = QtWidgets.QLineEdit(self.centralwidget)
        self.dataMagZ.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataMagZ.setAlignment(QtCore.Qt.AlignCenter)
        self.dataMagZ.setObjectName("dataMagZ")
        self.gridLayout.addWidget(self.dataMagZ, 3, 3, 1, 1)
        self.dataGyroY = QtWidgets.QLineEdit(self.centralwidget)
        self.dataGyroY.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataGyroY.setAlignment(QtCore.Qt.AlignCenter)
        self.dataGyroY.setObjectName("dataGyroY")
        self.gridLayout.addWidget(self.dataGyroY, 2, 2, 1, 1)
        self.dataMagY = QtWidgets.QLineEdit(self.centralwidget)
        self.dataMagY.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataMagY.setAlignment(QtCore.Qt.AlignCenter)
        self.dataMagY.setObjectName("dataMagY")
        self.gridLayout.addWidget(self.dataMagY, 3, 2, 1, 1)
        self.dataGyroZ = QtWidgets.QLineEdit(self.centralwidget)
        self.dataGyroZ.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataGyroZ.setAlignment(QtCore.Qt.AlignCenter)
        self.dataGyroZ.setObjectName("dataGyroZ")
        self.gridLayout.addWidget(self.dataGyroZ, 2, 3, 1, 1)
        self.dataAccZ = QtWidgets.QLineEdit(self.centralwidget)
        self.dataAccZ.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.dataAccZ.setAlignment(QtCore.Qt.AlignCenter)
        self.dataAccZ.setObjectName("dataAccZ")
        self.gridLayout.addWidget(self.dataAccZ, 1, 3, 1, 1)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 4, 3, 1, 1)
        self.spinIMU = QtWidgets.QSpinBox(self.centralwidget)
        self.spinIMU.setMaximum(4)
        self.spinIMU.setObjectName("spinIMU")
        self.gridLayout.addWidget(self.spinIMU, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("QLineEdit {background-color: #33cc33;};")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 4, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setStyleSheet("QLineEdit {background-color: #cc3333;};")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 4, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 4)
        self.gridLayout.setColumnStretch(2, 4)
        self.gridLayout.setColumnStretch(3, 4)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SK8 Calibration"))
        self.lblPort.setText(_translate("MainWindow", "Dongle serial port:"))
        self.lblDevices.setText(_translate("MainWindow", "Available BLE devices:"))
        self.btnRefresh.setText(_translate("MainWindow", "Begin scan"))
        self.btnCancelScan.setText(_translate("MainWindow", "Cancel scan"))
        self.btnConnect.setText(_translate("MainWindow", "Connect device"))
        self.btnMag.setText(_translate("MainWindow", "Magnetometer"))
        self.btnGyro.setText(_translate("MainWindow", "Gyroscope"))
        self.btnAcc.setText(_translate("MainWindow", "Accelerometer"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.spinIMU.setPrefix(_translate("MainWindow", "Using IMU #"))
        self.lineEdit.setText(_translate("MainWindow", "Calibrated"))
        self.lineEdit_2.setText(_translate("MainWindow", "Uncalibrated"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

