# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sk8_acc_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AccDialog(object):
    def setupUi(self, AccDialog):
        AccDialog.setObjectName("AccDialog")
        AccDialog.resize(683, 473)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AccDialog.sizePolicy().hasHeightForWidth())
        AccDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AccDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(AccDialog)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dataAccX = QtWidgets.QLineEdit(AccDialog)
        self.dataAccX.setAlignment(QtCore.Qt.AlignCenter)
        self.dataAccX.setReadOnly(True)
        self.dataAccX.setObjectName("dataAccX")
        self.gridLayout_2.addWidget(self.dataAccX, 0, 0, 1, 1)
        self.dataAccY = QtWidgets.QLineEdit(AccDialog)
        self.dataAccY.setAlignment(QtCore.Qt.AlignCenter)
        self.dataAccY.setReadOnly(True)
        self.dataAccY.setObjectName("dataAccY")
        self.gridLayout_2.addWidget(self.dataAccY, 0, 1, 1, 1)
        self.dataAccZ = QtWidgets.QLineEdit(AccDialog)
        self.dataAccZ.setAlignment(QtCore.Qt.AlignCenter)
        self.dataAccZ.setReadOnly(True)
        self.dataAccZ.setObjectName("dataAccZ")
        self.gridLayout_2.addWidget(self.dataAccZ, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.progSamples = QtWidgets.QProgressBar(AccDialog)
        self.progSamples.setProperty("value", 0)
        self.progSamples.setObjectName("progSamples")
        self.verticalLayout.addWidget(self.progSamples)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AccDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.btnPosX = QtWidgets.QPushButton(AccDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPosX.sizePolicy().hasHeightForWidth())
        self.btnPosX.setSizePolicy(sizePolicy)
        self.btnPosX.setObjectName("btnPosX")
        self.gridLayout.addWidget(self.btnPosX, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(AccDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btnPosY = QtWidgets.QPushButton(AccDialog)
        self.btnPosY.setEnabled(False)
        self.btnPosY.setObjectName("btnPosY")
        self.gridLayout.addWidget(self.btnPosY, 3, 1, 1, 1)
        self.btnPosZ = QtWidgets.QPushButton(AccDialog)
        self.btnPosZ.setEnabled(False)
        self.btnPosZ.setObjectName("btnPosZ")
        self.gridLayout.addWidget(self.btnPosZ, 5, 1, 1, 1)
        self.btnNegX = QtWidgets.QPushButton(AccDialog)
        self.btnNegX.setEnabled(False)
        self.btnNegX.setObjectName("btnNegX")
        self.gridLayout.addWidget(self.btnNegX, 2, 1, 1, 1)
        self.btnNegY = QtWidgets.QPushButton(AccDialog)
        self.btnNegY.setEnabled(False)
        self.btnNegY.setObjectName("btnNegY")
        self.gridLayout.addWidget(self.btnNegY, 4, 1, 1, 1)
        self.btnNegZ = QtWidgets.QPushButton(AccDialog)
        self.btnNegZ.setEnabled(False)
        self.btnNegZ.setObjectName("btnNegZ")
        self.gridLayout.addWidget(self.btnNegZ, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(AccDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(AccDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(AccDialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(AccDialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(AccDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOK = QtWidgets.QPushButton(AccDialog)
        self.btnOK.setEnabled(False)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(AccDialog)
        QtCore.QMetaObject.connectSlotsByName(AccDialog)

    def retranslateUi(self, AccDialog):
        _translate = QtCore.QCoreApplication.translate
        AccDialog.setWindowTitle(_translate("AccDialog", "Accelerometer calibration"))
        self.label_2.setText(_translate("AccDialog", "Point each axis of the IMU vertically downwards in turn, then click the OK button while keeping the device still. The current accelerometer readings are also shown below."))
        self.progSamples.setFormat(_translate("AccDialog", "%p% samples collected"))
        self.label.setText(_translate("AccDialog", "+X axis"))
        self.btnPosX.setText(_translate("AccDialog", "Record +X"))
        self.label_3.setText(_translate("AccDialog", "-X axis"))
        self.btnPosY.setText(_translate("AccDialog", "Record +Y"))
        self.btnPosZ.setText(_translate("AccDialog", "Record +Z"))
        self.btnNegX.setText(_translate("AccDialog", "Record -X"))
        self.btnNegY.setText(_translate("AccDialog", "Record -Y"))
        self.btnNegZ.setText(_translate("AccDialog", "Record -Z"))
        self.label_4.setText(_translate("AccDialog", "+Y axis"))
        self.label_5.setText(_translate("AccDialog", "-Y axis"))
        self.label_6.setText(_translate("AccDialog", "+Z axis"))
        self.label_7.setText(_translate("AccDialog", "-Z axis"))
        self.btnCancel.setText(_translate("AccDialog", "Cancel"))
        self.btnOK.setText(_translate("AccDialog", "OK"))

