# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sk8_mag_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MagDialog(object):
    def setupUi(self, MagDialog):
        MagDialog.setObjectName("MagDialog")
        MagDialog.resize(691, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(MagDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(MagDialog)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dataMagX = QtWidgets.QLineEdit(MagDialog)
        self.dataMagX.setAlignment(QtCore.Qt.AlignCenter)
        self.dataMagX.setReadOnly(True)
        self.dataMagX.setObjectName("dataMagX")
        self.gridLayout_2.addWidget(self.dataMagX, 0, 0, 1, 1)
        self.dataMagY = QtWidgets.QLineEdit(MagDialog)
        self.dataMagY.setAlignment(QtCore.Qt.AlignCenter)
        self.dataMagY.setReadOnly(True)
        self.dataMagY.setObjectName("dataMagY")
        self.gridLayout_2.addWidget(self.dataMagY, 0, 1, 1, 1)
        self.dataMagZ = QtWidgets.QLineEdit(MagDialog)
        self.dataMagZ.setAlignment(QtCore.Qt.AlignCenter)
        self.dataMagZ.setReadOnly(True)
        self.dataMagZ.setObjectName("dataMagZ")
        self.gridLayout_2.addWidget(self.dataMagZ, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(MagDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.btnPosX = QtWidgets.QPushButton(MagDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPosX.sizePolicy().hasHeightForWidth())
        self.btnPosX.setSizePolicy(sizePolicy)
        self.btnPosX.setObjectName("btnPosX")
        self.gridLayout.addWidget(self.btnPosX, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(MagDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btnPosY = QtWidgets.QPushButton(MagDialog)
        self.btnPosY.setEnabled(False)
        self.btnPosY.setObjectName("btnPosY")
        self.gridLayout.addWidget(self.btnPosY, 3, 1, 1, 1)
        self.btnPosZ = QtWidgets.QPushButton(MagDialog)
        self.btnPosZ.setEnabled(False)
        self.btnPosZ.setObjectName("btnPosZ")
        self.gridLayout.addWidget(self.btnPosZ, 5, 1, 1, 1)
        self.btnNegX = QtWidgets.QPushButton(MagDialog)
        self.btnNegX.setEnabled(False)
        self.btnNegX.setObjectName("btnNegX")
        self.gridLayout.addWidget(self.btnNegX, 2, 1, 1, 1)
        self.btnNegY = QtWidgets.QPushButton(MagDialog)
        self.btnNegY.setEnabled(False)
        self.btnNegY.setObjectName("btnNegY")
        self.gridLayout.addWidget(self.btnNegY, 4, 1, 1, 1)
        self.btnNegZ = QtWidgets.QPushButton(MagDialog)
        self.btnNegZ.setEnabled(False)
        self.btnNegZ.setObjectName("btnNegZ")
        self.gridLayout.addWidget(self.btnNegZ, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(MagDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(MagDialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(MagDialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(MagDialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(MagDialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOK = QtWidgets.QPushButton(MagDialog)
        self.btnOK.setEnabled(False)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(MagDialog)
        QtCore.QMetaObject.connectSlotsByName(MagDialog)

    def retranslateUi(self, MagDialog):
        _translate = QtCore.QCoreApplication.translate
        MagDialog.setWindowTitle(_translate("MagDialog", "Dialog"))
        self.label_2.setText(_translate("MagDialog", "Move the IMU to find the maximum positive and minimum negative value of the magnetic field along each axis, and click the \"Record\" button at each step."))
        self.label.setText(_translate("MagDialog", "+X axis"))
        self.btnPosX.setText(_translate("MagDialog", "Record +X"))
        self.label_3.setText(_translate("MagDialog", "-X axis"))
        self.btnPosY.setText(_translate("MagDialog", "Record +Y"))
        self.btnPosZ.setText(_translate("MagDialog", "Record +Z"))
        self.btnNegX.setText(_translate("MagDialog", "Record -X"))
        self.btnNegY.setText(_translate("MagDialog", "Record -Y"))
        self.btnNegZ.setText(_translate("MagDialog", "Record -Z"))
        self.label_4.setText(_translate("MagDialog", "+Y axis"))
        self.label_5.setText(_translate("MagDialog", "-Y axis"))
        self.label_6.setText(_translate("MagDialog", "+Z axis"))
        self.label_7.setText(_translate("MagDialog", "-Z axis"))
        self.btnCancel.setText(_translate("MagDialog", "Cancel"))
        self.btnOK.setText(_translate("MagDialog", "OK"))

